name: morpheus-servant-persistent
version: 0.1.0.0
github: "githubuser/morpheus-servant-persistent"
license: BSD-3-Clause
author: "Quincy Andelin"
maintainer: "quincy.andelin@evernow.com"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/morpheus-servant-persistent#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - data-default
  - envy
  - esqueleto
  - file-embed
  - http-media
  - monad-logger
  - morpheus-graphql
  - morpheus-graphql-core
  - morpheus-graphql-server
  - mtl
  - optparse-applicative
  - persistent
  - persistent-postgresql
  - servant-server
  - string-conversions
  - text
  - time
  - transformers
  - unix
  - unliftio
  - unliftio-core
  - warp
  - wai
  - wai-cors
  - wai-extra

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  morpheus-servant-persistent-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - morpheus-servant-persistent

tests:
  morpheus-servant-persistent-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - morpheus-servant-persistent
